version: '3'

services:

  mysql:
    image: mysql:latest
    container_name: mysql
    command: --innodb-use-native-aio=0 --default-authentication-plugin=mysql_native_password
    restart: always
    tty: true
    volumes:
      - "./mysql/schema.sql:/docker-entrypoint-initdb.d/1.sql"
      - "./mysql/data.sql:/docker-entrypoint-initdb.d/2.sql"
    environment:
      - MYSQL_DATABASE=db
      - MYSQL_ROOT_USER=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - netdesafio2

  node:
    build:
      context: ./node
      dockerfile: Dockerfile
    container_name: node
    volumes:
      - "./node:/app"
    networks:
      - netdesafio2
    depends_on:
      - mysql
    command: sh -c "dockerize -wait tcp://mysql:3306 -timeout 300s -wait-retry-interval 10s node index.js"

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx
    networks:
      - netdesafio2
    ports:
      - "8080:80"
    depends_on:
      - node
    command: sh -c "dockerize -wait http://node:3000 -timeout 300s -wait-retry-interval 10s nginx -g 'daemon off;'"

networks:
  netdesafio2:
    driver: bridge
    
